---

# Process a single _nexus_repos_global_list for configured formats and apply default values for type.

# @todo: refactor with easier syntax once the 'flip' filter is released (possibly in ansible 2.8)
# See the following related PRs/issues.
# - https://github.com/ansible/ansible/pull/46340
# - https://github.com/ansible/ansible/pull/46255
# - https://github.com/ansible/ansible/issues/46215
# - https://github.com/pallets/jinja/pull/906
- name: Initialize facts
  set_fact:
    _nexus_repos_maven_proxy: []
    _nexus_repos_maven_hosted: []
    _nexus_repos_maven_group: []
    _nexus_repos_docker_proxy: []
    _nexus_repos_docker_hosted: []
    _nexus_repos_docker_group: []
    _nexus_repos_pypi_proxy: []
    _nexus_repos_pypi_hosted: []
    _nexus_repos_pypi_group: []
    _nexus_repos_raw_proxy: []
    _nexus_repos_raw_hosted: []
    _nexus_repos_raw_group: []
    _nexus_repos_rubygems_proxy: []
    _nexus_repos_rubygems_hosted: []
    _nexus_repos_rubygems_group: []
    _nexus_repos_bower_proxy: []
    _nexus_repos_bower_hosted: []
    _nexus_repos_bower_group: []
    _nexus_repos_npm_proxy: []
    _nexus_repos_npm_hosted: []
    _nexus_repos_npm_group: []
    _nexus_repos_nuget_proxy: []
    _nexus_repos_nuget_hosted: []
    _nexus_repos_nuget_group: []
    _nexus_repos_gitlfs_hosted: []
    _nexus_repos_yum_proxy: []
    _nexus_repos_yum_hosted: []
    _nexus_repos_yum_group: []
    _nexus_repos_apt_proxy: []
    _nexus_repos_apt_hosted: []
    _nexus_repos_helm_proxy: []
    _nexus_repos_helm_hosted: []
    _nexus_repos_r_proxy: []
    _nexus_repos_r_hosted: []
    _nexus_repos_r_group: []
    _nexus_repos_p2_proxy: []
    _nexus_repos_go_proxy: []
    _nexus_repos_go_group: []

- name: Process definitions for maven
  when: nexus_config_maven | bool
  block:
    - name: apply defaults to maven proxy repos
      set_fact:
        _nexus_repos_maven_proxy: "{{ _nexus_repos_maven_proxy + [_nexus_repos_maven_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_maven_proxy }}"

    - name: apply defaults to maven hosted repos
      set_fact:
        _nexus_repos_maven_hosted: "{{ _nexus_repos_maven_hosted + [_nexus_repos_maven_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_maven_hosted }}"

    - name: apply defaults to maven group repos
      set_fact:
        _nexus_repos_maven_group: "{{ _nexus_repos_maven_group + [_nexus_repos_maven_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_maven_group }}"

    - name: Add maven repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_maven_proxy | map('combine', {"format": "maven2", "type": "proxy"}) | list)
            +
            (_nexus_repos_maven_hosted | map('combine', {"format": "maven2", "type": "hosted"}) | list)
            +
            (_nexus_repos_maven_group | map('combine', {"format": "maven2", "type": "group"}) | list)
          }}

- name: Process definitions for docker
  when: nexus_config_docker | bool
  block:

    - name: apply defaults to docker proxy repos
      set_fact:
        _nexus_repos_docker_proxy: "{{ _nexus_repos_docker_proxy + [_nexus_repos_docker_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_docker_proxy }}"

    - name: apply defaults to docker hosted repos
      set_fact:
        _nexus_repos_docker_hosted: "{{ _nexus_repos_docker_hosted + [_nexus_repos_docker_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_docker_hosted }}"

    - name: apply defaults to docker group repos
      set_fact:
        _nexus_repos_docker_group: "{{ _nexus_repos_docker_group + [_nexus_repos_docker_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_docker_group }}"

    - name: Add docker repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_docker_proxy | map('combine', {"format": "docker", "type": "proxy"}) | list)
            +
            (_nexus_repos_docker_hosted | map('combine', {"format": "docker", "type": "hosted"}) | list)
            +
            (_nexus_repos_docker_group | map('combine', {"format": "docker", "type": "group"}) | list)
          }}

- name: Process definitions for pypi
  when: nexus_config_pypi | bool
  block:

    - name: apply defaults to pypi proxy repos
      set_fact:
        _nexus_repos_pypi_proxy: "{{ _nexus_repos_pypi_proxy + [_nexus_repos_pypi_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_pypi_proxy }}"

    - name: apply defaults to pypi hosted repos
      set_fact:
        _nexus_repos_pypi_hosted: "{{ _nexus_repos_pypi_hosted + [_nexus_repos_pypi_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_pypi_hosted }}"

    - name: apply defaults to pypi group repos
      set_fact:
        _nexus_repos_pypi_group: "{{ _nexus_repos_pypi_group + [_nexus_repos_pypi_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_pypi_group }}"

    - name: Add pypi repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_pypi_proxy | map('combine', {"format": "pypi", "type": "proxy"}) | list)
            +
            (_nexus_repos_pypi_hosted | map('combine', {"format": "pypi", "type": "hosted"}) | list)
            +
            (_nexus_repos_pypi_group | map('combine', {"format": "pypi", "type": "group"}) | list)
          }}

- name: Process definitions for raw repositories
  when: nexus_config_raw | bool
  block:

    - name: apply defaults to raw proxy repos
      set_fact:
        _nexus_repos_raw_proxy: "{{ _nexus_repos_raw_proxy + [_nexus_repos_raw_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_raw_proxy }}"

    - name: apply defaults to raw hosted repos
      set_fact:
        _nexus_repos_raw_hosted: "{{ _nexus_repos_raw_hosted + [_nexus_repos_raw_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_raw_hosted }}"

    - name: apply defaults to raw group repos
      set_fact:
        _nexus_repos_raw_group: "{{ _nexus_repos_raw_group + [_nexus_repos_raw_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_raw_group }}"

    - name: Add raw repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_raw_proxy | map('combine', {"format": "raw", "type": "proxy"}) | list)
            +
            (_nexus_repos_raw_hosted | map('combine', {"format": "raw", "type": "hosted"}) | list)
            +
            (_nexus_repos_raw_group | map('combine', {"format": "raw", "type": "group"}) | list)
          }}

- name: Process definitions for rubygems repositories
  when: nexus_config_rubygems | bool
  block:

    - name: apply defaults to rubygems proxy repos
      set_fact:
        _nexus_repos_rubygems_proxy: "{{ _nexus_repos_rubygems_proxy + [_nexus_repos_rubygems_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_rubygems_proxy }}"

    - name: apply defaults to rubygems hosted repos
      set_fact:
        _nexus_repos_rubygems_hosted: "{{ _nexus_repos_rubygems_hosted + [_nexus_repos_rubygems_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_rubygems_hosted }}"

    - name: apply defaults to rubygems group repos
      set_fact:
        _nexus_repos_rubygems_group: "{{ _nexus_repos_rubygems_group + [_nexus_repos_rubygems_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_rubygems_group }}"

    - name: Add rubygems repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_rubygems_proxy | map('combine', {"format": "rubygems", "type": "proxy"}) | list)
            +
            (_nexus_repos_rubygems_hosted | map('combine', {"format": "rubygems", "type": "hosted"}) | list)
            +
            (_nexus_repos_rubygems_group | map('combine', {"format": "rubygems", "type": "group"}) | list)
          }}

- name: Process definitions for bower repositories
  when: nexus_config_bower | bool
  block:

    - name: apply defaults to bower proxy repos
      set_fact:
        _nexus_repos_bower_proxy: "{{ _nexus_repos_bower_proxy + [_nexus_repos_bower_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_bower_proxy }}"

    - name: apply defaults to bower hosted repos
      set_fact:
        _nexus_repos_bower_hosted: "{{ _nexus_repos_bower_hosted + [_nexus_repos_bower_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_bower_hosted }}"

    - name: apply defaults to bower group repos
      set_fact:
        _nexus_repos_bower_group: "{{ _nexus_repos_bower_group + [_nexus_repos_bower_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_bower_group }}"

    - name: Add bower repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (nexus_repos_bower_proxy | map('combine', {"format": "bower", "type": "proxy"}) | list)
            +
            (nexus_repos_bower_hosted | map('combine', {"format": "bower", "type": "hosted"}) | list)
            +
            (nexus_repos_bower_group | map('combine', {"format": "bower", "type": "group"}) | list)
          }}

- name: Process definitions for npm repositories
  when: nexus_config_npm | bool
  block:

    - name: apply defaults to npm proxy repos
      set_fact:
        _nexus_repos_npm_proxy: "{{ _nexus_repos_npm_proxy + [_nexus_repos_npm_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_npm_proxy }}"

    - name: apply defaults to npm hosted repos
      set_fact:
        _nexus_repos_npm_hosted: "{{ _nexus_repos_npm_hosted + [_nexus_repos_npm_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_npm_hosted }}"

    - name: apply defaults to npm group repos
      set_fact:
        _nexus_repos_npm_group: "{{ _nexus_repos_npm_group + [_nexus_repos_npm_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_npm_group }}"

    - name: Add npm repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_npm_proxy | map('combine', {"format": "npm", "type": "proxy"}) | list)
            +
            (_nexus_repos_npm_hosted | map('combine', {"format": "npm", "type": "hosted"}) | list)
            +
            (_nexus_repos_npm_group | map('combine', {"format": "npm", "type": "group"}) | list)
          }}

- name: Process definitions for nuget repositories
  when: nexus_config_nuget | bool
  block:

    - name: apply defaults to nuget proxy repos
      set_fact:
        _nexus_repos_nuget_proxy: "{{ _nexus_repos_nuget_proxy + [_nexus_repos_nuget_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_nuget_proxy }}"

    - name: apply defaults to nuget hosted repos
      set_fact:
        _nexus_repos_nuget_hosted: "{{ _nexus_repos_nuget_hosted + [_nexus_repos_nuget_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_nuget_hosted }}"

    - name: apply defaults to nuget group repos
      set_fact:
        _nexus_repos_nuget_group: "{{ _nexus_repos_nuget_group + [_nexus_repos_nuget_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_nuget_group }}"

    - name: Add nuget repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_nuget_proxy | map('combine', {"format": "nuget", "type": "proxy"}) | list)
            +
            (_nexus_repos_nuget_hosted | map('combine', {"format": "nuget", "type": "hosted"}) | list)
            +
            (_nexus_repos_nuget_group | map('combine', {"format": "nuget", "type": "group"}) | list)
          }}

- name: Process definitions for gitlfs repositories
  when: nexus_config_gitlfs | bool
  block:

    - name: apply defaults to gitlfs hosted repos
      set_fact:
        _nexus_repos_gitlfs_hosted: "{{ _nexus_repos_gitlfs_hosted + [_nexus_repos_gitlfs_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_gitlfs_hosted }}"

    - name: Add gitlfs repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_gitlfs_hosted | map('combine', {"format": "gitlfs", "type": "hosted"}) | list)
          }}

- name: Process definitions for yum repositories
  when: nexus_config_yum | bool
  block:

    - name: apply defaults to yum proxy repos
      set_fact:
        _nexus_repos_yum_proxy: "{{ _nexus_repos_yum_proxy + [_nexus_repos_yum_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_yum_proxy }}"

    - name: apply defaults to yum hosted repos
      set_fact:
        _nexus_repos_yum_hosted: "{{ _nexus_repos_yum_hosted + [_nexus_repos_yum_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_yum_hosted }}"

    - name: apply defaults to yum group repos
      set_fact:
        _nexus_repos_yum_group: "{{ _nexus_repos_yum_group + [_nexus_repos_yum_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_yum_group }}"

    - name: Add yum repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_yum_proxy | map('combine', {"format": "yum", "type": "proxy"}) | list)
            +
            (_nexus_repos_yum_hosted | map('combine', {"format": "yum", "type": "hosted"}) | list)
            +
            (_nexus_repos_yum_group | map('combine', {"format": "yum", "type": "group"}) | list)
          }}

- name: Process definitions for apt repositories
  when: nexus_config_apt | bool
  block:

    - name: apply defaults to apt proxy repos
      set_fact:
        _nexus_repos_apt_proxy: "{{ _nexus_repos_apt_proxy + [_nexus_repos_apt_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_apt_proxy }}"

    - name: apply defaults to apt hosted repos
      set_fact:
        _nexus_repos_apt_hosted: "{{ _nexus_repos_apt_hosted + [_nexus_repos_apt_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_apt_hosted }}"

    - name: Add apt repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_apt_proxy | map('combine', {"format": "apt", "type": "proxy"}) | list)
            +
            (_nexus_repos_apt_hosted | map('combine', {"format": "apt", "type": "hosted"}) | list)
          }}

- name: Process definitions for helm repositories
  when: nexus_config_helm | bool
  block:

    - name: apply defaults to helm proxy repos
      set_fact:
        _nexus_repos_helm_proxy: "{{ _nexus_repos_helm_proxy + [_nexus_repos_helm_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_helm_proxy }}"

    - name: apply defaults to helm hosted repos
      set_fact:
        _nexus_repos_helm_hosted: "{{ _nexus_repos_helm_hosted + [_nexus_repos_helm_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_helm_hosted }}"

    - name: Add helm repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_helm_proxy | map('combine', {"format": "helm", "type": "proxy"}) | list)
            +
            (_nexus_repos_helm_hosted | map('combine', {"format": "helm", "type": "hosted"}) | list)
          }}

- name: Process definitions for r
  when: nexus_config_r | bool
  block:

    - name: apply defaults to r proxy repos
      set_fact:
        _nexus_repos_r_proxy: "{{ _nexus_repos_r_proxy + [_nexus_repos_r_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_r_proxy }}"

    - name: apply defaults to r hosted repos
      set_fact:
        _nexus_repos_r_hosted: "{{ _nexus_repos_r_hosted + [_nexus_repos_r_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_r_hosted }}"

    - name: apply defaults to r group repos
      set_fact:
        _nexus_repos_r_group: "{{ _nexus_repos_r_group + [_nexus_repos_r_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_r_group }}"

    - name: Add r repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_r_proxy | map('combine', {"format": "r", "type": "proxy"}) | list)
            +
            (_nexus_repos_r_hosted | map('combine', {"format": "r", "type": "hosted"}) | list)
            +
            (_nexus_repos_r_group | map('combine', {"format": "r", "type": "group"}) | list)
          }}

- name: Process definitions for p2 repositories
  when: nexus_config_p2 | bool
  block:

    - name: apply defaults to p2 proxy repos
      set_fact:
        _nexus_repos_p2_proxy: "{{ _nexus_repos_p2_proxy + [_nexus_repos_p2_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_p2_proxy }}"

    - name: Add p2 repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_p2_proxy | map('combine', {"format": "p2", "type": "proxy"}) | list)
          }}

- name: Process definitions for conda
  when: nexus_config_conda | bool
  block:

    - name: apply defaults to conda proxy repos
      set_fact:
        _nexus_repos_r_proxy: "{{ _nexus_repos_r_proxy + [_nexus_repos_conda_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_r_proxy }}"

    - name: Add conda repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_r_proxy | map('combine', {"format": "conda", "type": "proxy"}) | list)
          }}

- name: Process definitions for go repositories
  when: nexus_config_go | bool
  block:

    - name: apply defaults to go proxy repos
      set_fact:
        _nexus_repos_go_proxy: "{{ _nexus_repos_go_proxy + [_nexus_repos_go_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_go_proxy }}"

    - name: apply defaults to go group repos
      set_fact:
        _nexus_repos_go_group: "{{ _nexus_repos_go_group + [_nexus_repos_go_defaults | combine(item)] }}"
      loop: "{{ nexus_repos_go_group }}"

    - name: Add go repositories to global repos list
      set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (_nexus_repos_go_proxy | map('combine', {"format": "go", "type": "proxy"}) | list)
            +
            (_nexus_repos_go_group | map('combine', {"format": "go", "type": "group"}) | list)
          }}
